### PR TITLE
Update README to show Coupon support in Checkout

### PR DESCRIPTION
**Pull request by tmarek-stripe**
image

### CODE REVIEW

**Comment by cjavilla-stripe** [comment]
Does it tho? Do we need to add that allow_promotion_code call to all of the checkout session create calls?

**Comment by adreyfus-stripe** [comment]
What about updating to:

Supports coupons via [allow_promotion_code](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-allow_promotion_codes) parameter

**Comment by tmarek-stripe** [comment]
SGTM
image

**Review by cjavilla-stripe — APPROVED** [review]
lgtm

**Pull request merged**
